module.exports = {
  viewAccount: "View Account",
  signIn: "Sign In",
  signOut: "Sign Out",
  changeUsername: "Change",
  loggedInUsername: "ally@gmail.com",
  loggedOutUsername: "Guest",
  newCallButton: "New Invitation",
  callingAs: "Calling as",
  searchPlaceholder: "Search...",
  getLinkText: "Get Link",
  callNamePlaceholder: "Orange Prickly Badger",
  inviteExpireIn: "Invitation will expire in",
  sampleCallURL: "http://loop.dev.mozaws.net/calls/IRzK5l843AxgKTorMKh7XmhR0QzkSNvuVJVD7ZWpeYjzVWe6BhRPYfd6M5mdTDguvP0QXO0pnd-Ac23-ufDtoKUkvaIUZ8FSo5AHU0FBXqwtO6_ZFSwL1mX3brGHICs6xfCfJ6X0zRVRR-bzM7Bg9glFAIo",
  shareThisLinkWith: "Share this link with",
  contactManagement: "Add or Import Contacts",
  callHistory: "Call History",
  clearHistory: "Clear",
  invitationList: "Your Invitations",
  expired: "Expired",
  endCall: "Hang Up"
};
